# Simple guide to exract model summary,standard error coefficeints,odds ratio and covariance matrix using statsmodels

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
#print(iris)

In [2]:
X = iris["data"][:,]  # petal width
y = (iris["target"]==2).astype(np.int)

In [3]:
import statsmodels.api as sm

#fitting logistic regression to iris data set using statsmodels GLM
#We are fitting with default family function and link function
# Refer to the link for family of functions that you can try with GLM
# http://www.statsmodels.org/stable/glm.html#examples
model = sm.GLM(y, X).fit()

C:\Users\inpganavar\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [4]:
#Model object has several attributes,let's us print the model symmmary as of now
#refer to the following link for model object charcteristics : http://www.statsmodels.org/stable/generated/statsmodels.genmod.generalized_linear_model.GLMResults.html#statsmodels.genmod.generalized_linear_model.GLMResults
print(model.summary())

                  Generalized Linear Model Regression Results                  
Dep. Variable:                      y   No. Observations:                   150
Model:                            GLM   Df Residuals:                       146
Model Family:                Gaussian   Df Model:                             3
Link Function:               identity   Scale:              0.09121510438801805
Method:                          IRLS   Log-Likelihood:                 -31.224
Date:                Thu, 05 Apr 2018   Deviance:                        13.317
Time:                        11:34:24   Pearson chi2:                      13.3
No. Iterations:                     2                                          
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.1448      0.068     -2.130      0.033      -0.278      -0.012
x2             0.1374      0.079      1.744

In [5]:
#standard error of coefficient can be retrieved by
model.bse

array([0.06799117, 0.07878605, 0.07838033, 0.12939471])

In [6]:
#model variance/covariance parameters can be retrieved by
model.cov_params()

array([[ 0.0046228 , -0.00519157, -0.00428013,  0.00418749],
       [-0.00519157,  0.00620724,  0.00416021, -0.00350695],
       [-0.00428013,  0.00416021,  0.00614348, -0.00900856],
       [ 0.00418749, -0.00350695, -0.00900856,  0.01674299]])

In [7]:
#to get the odds ratio,
np.exp(model.params)

array([0.86520448, 1.1472691 , 1.0178213 , 1.79115056])

In [8]:
#to get the confidence intervals
print(model.conf_int())

[[-0.27804964 -0.01152916]
 [-0.01703341  0.29180225]
 [-0.13595826  0.17128698]
 [ 0.3292492   0.83646716]]
